### PR TITLE
Use xcp-idl for command-line parsing

### PR DESCRIPTION
**Pull request by djs55**
This will require making changes to the init.d script, so this needs to be synchronised with xen-api-libs-specs.

### CODE REVIEW

**Comment by euanh** [comment]
@djs55: Ping!

**Comment by djs55** [comment]
This probably needs a dependency added to the spec file

**Comment by euanh** [comment]
@djs55: The last run failed building obuild. Grrr.  That was some time ago, so I've kicked off another Travis job to see what's new.

**Comment by euanh** [comment]
@djs55: Slightly concerned to see that Travis marked job 4.3 'green' even though the log shows that it failed and returned a nonzero exit code:
https://travis-ci.org/xapi-project/forkexecd/jobs/36394750

**Comment by euanh** [comment]
This pull request seems to be stuck.

**Pull request closed without merging**
