### PR TITLE
CP-15745: Use xenserver-build-env for the travis build

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by johnelse** [comment]
Just seeing what travis thinks for now - might be able to add some tests too :open_mouth:

**Comment by johnelse** [comment]
This needs refactoring to

* clear up spurious `sudo`s
* add a test vector which allows the test to run in a sensible time, but includes `max_fds`

**Comment by simonjbeaumont** [comment]
> This needs refactoring to
* clear up spurious `sudo`s
*    add a test vector which allows the test to run in a sensible time, but includes `max_fds`



:+1:

**Comment by johnelse** [comment]
I forgot another thing

* use a trap in the test script to make sure `fe` gets killed

**Pull request merged**
